### ISSUE TITLE
isPC has been deprecated, but some scripts appear to still use it

### ISSUE THREAD

**Issue by jacobjorvang** [foundry-vtt-community/macros#152]
foundry_community_macros/module-specific/resolve_surprise.js:135:    .filter((pc) => pc.actor.isPC && pc.actor.data.type === "character")

foundry_community_macros/module-specific/resolve_surprise.js:144:    .filter((pc) => pc.actor.isPC && pc.actor.data.type === "character")

foundry_community_macros/module-specific/resolve_surprise.js:151:    .filter((ec) => ec.actor.isPC === false && ec.data.disposition === -1)

foundry_community_macros/module-specific/resolve_surprise.js:160:    .filter((ec) => ec.actor.isPC === false && ec.data.disposition === -1)

foundry_community_macros/misc/award_party_xp.js:5:    let actors = game.actors.entities.filter(e => e.data.type === 'character' && e.isPC);

**Comment by Stratlin** [comment]
I encountered this in the following macro:
https://github.com/foundry-vtt-community/macros/blob/1cc210e611333771a24056315f470fce5cd2e865/misc/award_party_xp.js#L5

I was able to quick and dirty fix it in that case by changing .isPc to .hasPlayerOwner . I haven't had time to extensively test it and I don't know if the fix is that simple for all macros but it seems to be working in that use case.

**Comment by AnthonyVadala** [comment]
`module-specific/resolve_surprise.js` (and several other macros) are being removed in the upcoming v9 version of this module due to the module it depends no longer being updated. 

`misc/award_party_xp.js` has been updated to work in the v9 development branch.
