### ISSUE TITLE
PF2e - Rest for the night does not work anymore

### ISSUE THREAD

**Issue by DieterKosken** [foundry-vtt-community/macros#229]
Hi, 

Looks like its failing on 
'CONFIG.PF2E.Actor.entityClasses.character;'

entityClasses is undefined.

**Comment by willvk** [comment]
I had a look at this macro. Personally I'm not sure updating it is super crucial since I know my players just use the Utility button provided by the Token-Action-Hud module (which is basically gospel with me and my friends). I even tried looking through the module code to see if I could extract their implementation then its just a copy pasta, but no immediate success.
https://foundryvtt.com/packages/token-action-hud/
I'd recommend removing it since its provided by a common module, just my 2c.

**Comment by AnthonyVadala** [comment]
This macro has been removed as of update v9.8 due to how common Token Action HUD is.
