### ISSUE TITLE
Help with wall resizing macro in 0.8.x

### ISSUE THREAD

**Issue by ravingdragoon** [foundry-vtt-community/macros#243]
Can anyone help me update this macro to work in 0.8.x? Perhaps @mainframe97 since they helped with a similar issue a few months ago involving doors? I am running Curse of Strahd, and am having to resize a lot of maps and then redraw all the walls.

let scale = 2;
canvas.scene.update({
  walls: duplicate(canvas.scene.data.walls.map(w => {
    w.c = w.c.map(x => x * scale);
    return w;
  }))
});

**Comment by mainframe97** [comment]
Hi,

Try this macro

```
let scale = 2;

let oldWalls = canvas.scene.data.walls.map(w => {
  w = duplicate(w);
  w.c[0] = w.c[0] * scale;
  w.c[1] = w.c[1] * scale;
  w.c[2] = w.c[2] * scale;
  w.c[3] = w.c[3] * scale;
  return w;
});

canvas.scene.update({walls: oldWalls});
```

I just refactored yours while drawing inspiration from [misc/move_wall.js](https://github.com/foundry-vtt-community/macros/blob/main/misc/move_walls.js).

I'm not a huge expert in JS or Foundry VTT but yours probably failed because it used `w.c` instead of `w.data.c`, duplicate should give you a *.data duplicate but since it was used outside of a map function it did not (maybe, again not an expert).
In fact if you added the `.data` no error appear (at least in my test) but i could not make the update work.

**Comment by mainframe97** [comment]
Forgot to mention, as already stated in the other macro i linked, if you want to resize only one of the axis their order is the following:

0 = Node 1 X 
1 = Node 1 Y 
2 = Node 2 X 
3 = Node 2 Y

**Comment by ravingdragoon** [comment]
Works like a dream! Thank you so much for this!!!
